[tool.poetry]
name = "banking-system"
version = "0.1.0"
description = "My description"
authors = ["Badrkic Boris <zebrnjak88@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "[^3.11]"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
